---
title: "Topic Modelling"
output:
  word_document: default
  html_document: default
date: "2023-06-02"
---

```{r library}
library(rJava)
library(readxl)
library(tm)
library(topicmodels)
library(tidytext)
library(ggplot2)
library(dplyr)
library(tidyr)
```


```{r data hasil translate}
cleandata<- read.csv("D:/Data STATBIS ITS/Sem 6/Metode Data Tidak Terstruktur/Praktikum terjemahan/2043201062_Andryan.csv")
head(cleandata)
```

```{r corpus and dtm}
corpus_text<-Corpus(VectorSource(cleandata$Indo))
inspect(corpus_text)

DTM<-DocumentTermMatrix(corpus_text)
inspect(DTM)

```

```{r remove empty doc}
rowTotals<-apply(DTM,1,sum) #find the sum of word in each document
dtm.new<-DTM[rowTotals>0, ]#remove all docs wothout word
```

```{r define topic}
library(topicmodels)
ap_lda<-LDA(dtm.new, k=2, control = list(seed=1234))
ap_lda
```

```{r word topic probabilities}
library(tidytext)
ap_topics <- tidy(ap_lda, matrix = "beta")
ap_topics
```

```{r most term in each topic}
ap_top_terms <- ap_topics %>%
  group_by(topic) %>%
  slice_max(beta, n = 10) %>% 
  ungroup() %>%
  arrange(topic, -beta)
ap_top_terms %>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(beta, term, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  scale_y_reordered()
```

```{r difference in β between topic 1 and topic 2}
beta_wide <- ap_topics %>%
  mutate(topic = paste0("topic", topic)) %>%
  pivot_wider(names_from = topic, values_from = beta) %>% 
  filter(topic1 > .001 | topic2 > .001) %>%
  mutate(log_ratio = log2(topic2 / topic1))
beta_wide

beta_wide %>%
  group_by(direction = log_ratio > 0) %>%
  slice_max(abs(log_ratio), n=10) %>%
  ungroup() %>%
  mutate(term=reorder(term,log_ratio)) %>%
  ggplot(aes(log_ratio, term)) +
  geom_col() +
  labs(x="Log2 ratio of beta in topic 2 / topic 1", y=NULL)
```

```{r document-topic probabilities}
ap_documents <- tidy(ap_lda, matrix = "gamma")
ap_documents
```

```{r most common word}
tidy(dtm.new) %>%
  filter(document == 10) %>%
  arrange(desc(count))
```